#!/bin/bash

name=$1
sql="psql -U cms -h localhost cms -c "
title=$(grep "^#title" $1.muse | cut -d ' ' -f 2-)

$sql "INSERT INTO article (name) VALUES ('$name')"
$sql "INSERT INTO article_version (name, format, version, title)\
       VALUES ('$name', 'html', (SELECT COALESCE(MAX(version), 0) + 1 \
                                 FROM article_version WHERE name = '$name'), \
               '$title')"
