#!/usr/bin/env bash

set -e

input=$(mktemp)
chmod go+r $input

cat > $input

# The gressgraph parser is currently touchy about having a newline at the end
# of the file. Make sure that one is there.
echo "" >> $input

# The graph's ID will be the md5 hash of its chains.
id=$(md5sum $input | cut -d' ' -f1)

# Generate output, but only if this example hasn't been posted before.
if [ ! -e $id ]; then
   chmod u+w .
   mkdir $id
   mv $input $id/text.plain
   gressgraph < $id/text.plain > $id/vnd.graphviz
   twopi -Tsvg $id/vnd.graphviz > $id/image.svg+xml
   ln -s image.svg+xml $id/GET
fi

rm $input

echo -n $id
